2016-03-09 12:59:11+0300 [-] Log opened.
2016-03-09 12:59:11+0300 [-] PBServerFactory starting on 13333
2016-03-09 12:59:11+0300 [-] Starting factory <twisted.spread.pb.PBServerFactory instance at 0x02795918>
2016-03-09 12:59:11+0300 [-] Starting off the system
2016-03-09 12:59:43+0300 [-] Daily Thread initiating messenger
2016-03-09 12:59:43+0300 [-] this is the type extension
2016-03-09 12:59:43+0300 [-] extension has been disabled
2016-03-09 12:59:43+0300 [-] this is the type renewal
2016-03-09 12:59:44+0300 [-] this is the type clients
2016-03-09 12:59:44+0300 [-] clients has been disabled
2016-03-09 12:59:44+0300 [-] this is the type newinvoice
2016-03-09 12:59:44+0300 [-] New minimum invoice 6654
2016-03-09 12:59:44+0300 [-] New minimum invoice 6654
2016-03-09 12:59:44+0300 [-] this is the type birthday
2016-03-09 12:59:44+0300 [-] birthday has been disabled
2016-03-09 12:59:44+0300 [-] this is the type cheque
2016-03-09 12:59:44+0300 [-] this is the type balance
2016-03-09 12:59:44+0300 [-] 6 messages waiting to be sent
2016-03-09 12:59:44+0300 [-] Internet error
2016-03-09 12:59:44+0300 [-] False
2016-03-09 12:59:44+0300 [-] Internet error
2016-03-09 12:59:44+0300 [-] False
2016-03-09 12:59:44+0300 [-] Internet error
2016-03-09 12:59:44+0300 [-] False
2016-03-09 12:59:44+0300 [-] Internet error
2016-03-09 12:59:44+0300 [-] False
2016-03-09 12:59:44+0300 [-] Internet error
2016-03-09 12:59:44+0300 [-] False
2016-03-09 12:59:44+0300 [-] Internet error
2016-03-09 12:59:44+0300 [-] False
2016-03-09 13:00:06+0300 [-] Hourly Thread initiating messenger
2016-03-09 13:00:06+0300 [-] 6 messages waiting to be sent
2016-03-09 13:00:06+0300 [-] Internet error
2016-03-09 13:00:06+0300 [-] False
2016-03-09 13:00:06+0300 [-] Internet error
2016-03-09 13:00:06+0300 [-] False
2016-03-09 13:00:06+0300 [-] Internet error
2016-03-09 13:00:06+0300 [-] False
2016-03-09 13:00:06+0300 [-] Internet error
2016-03-09 13:00:06+0300 [-] False
2016-03-09 13:00:06+0300 [-] Internet error
2016-03-09 13:00:06+0300 [-] False
2016-03-09 13:00:06+0300 [-] Internet error
2016-03-09 13:00:06+0300 [-] False
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 3059 renewals
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 696 balances
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 696 clients
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 2109 expiries
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 1 cheques
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 1 bank
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 1 payee
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 1 cheque types
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 13 users
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with company information
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 0 names
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 4 group clients
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to request with 7 messages
2016-03-09 13:00:37+0300 [Broker,0,127.0.0.1] Server responding to outbox request
2016-03-09 13:00:39+0300 [Broker,0,127.0.0.1] Received SIGINT, shutting down.
2016-03-09 13:00:39+0300 [twisted.spread.pb.PBServerFactory] (TCP Port 13333 Closed)
2016-03-09 13:00:39+0300 [twisted.spread.pb.PBServerFactory] Stopping factory <twisted.spread.pb.PBServerFactory instance at 0x02795918>
2016-03-09 13:00:39+0300 [-] Connection close failed
	Traceback (most recent call last):
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "d:\python27\lib\site-packages\twisted\internet\base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "d:\python27\lib\site-packages\twisted\enterprise\adbapi.py", line 393, in finalClose
	    self._close(conn)
	--- <exception caught here> ---
	  File "d:\python27\lib\site-packages\twisted\enterprise\adbapi.py", line 439, in _close
	    conn.close()
	sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 6408 and this is thread id 712
	
2016-03-09 13:00:39+0300 [-] Connection close failed
	Traceback (most recent call last):
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 295, in addCallbacks
	    self._runCallbacks()
	  File "d:\python27\lib\site-packages\twisted\internet\defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "d:\python27\lib\site-packages\twisted\internet\base.py", line 429, in _continueFiring
	    callable(*args, **kwargs)
	  File "d:\python27\lib\site-packages\twisted\enterprise\adbapi.py", line 393, in finalClose
	    self._close(conn)
	--- <exception caught here> ---
	  File "d:\python27\lib\site-packages\twisted\enterprise\adbapi.py", line 439, in _close
	    conn.close()
	sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 6280 and this is thread id 712
	
2016-03-09 13:00:39+0300 [-] Main loop terminated.
